### ISSUE TITLE
Tests fail with `pytest.PytestConfigWarning: Unknown config option: timeout` with pytest 6+

### ISSUE THREAD

**Issue by homeworkprod** [samuelcolvin/rtoml#12]
I've encountered this error when testing locally with pytest 6.0.2 installed as well as in the build steps in #11.

The issue went away locally after I installed pytest 5.3.1 (i.e. the version pinned in `tests/requirements.txt`).

For example, the "test (3.8)" step has this output on the GitHub CI:
```
pytest --cov=rtoml
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
```

The "build py 3.8 on linux" step, however, has this:
```
+ pip install pytest
Collecting pytest
  Downloading pytest-6.1.0-py3-none-any.whl (272 kB)
```
followed by
```
+ sh -c 'pytest /project/tests -s'
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
```

**Comment by homeworkprod** [comment]
I could not find a `timeout` option in pytest's config documentation as well as its changelog.

What I found, though:
- a Python argument of that name to a few methods of classes `Testdir` and `RunResult`
- a configuration key `faulthandler_timeout` (but that *might* be something different)

I couldn't find a way to pin pytest to a specific version in GitHub CI, but I'm not familiar with it as I haven't used it so far.

Maybe just drop the configuration directive from the `[tool:pytest]` section in `setup.cfg` (and optionally change the pinned pytest version to 6.x, too)?

**Comment by samuelcolvin** [comment]
one line fix, just remove 

https://github.com/samuelcolvin/rtoml/blob/5d068fb4af656a379ee2d552ca09bd28290060d8/setup.cfg#L3

**Comment by homeworkprod** [comment]
Thanks for the confirmation. PR is at #13.
