### ISSUE TITLE
Provide wheels for Python 3.9

### ISSUE THREAD

**Issue by homeworkprod** [samuelcolvin/rtoml#14]
Hi Samuel,

would you mind providing wheels for Python 3.9?

**Comment by samuelcolvin** [comment]
fine by me, could you create a PR to generate them on CI.

**Comment by homeworkprod** [comment]
Naive attempt at #15. Results doesn't look good, though.

**Comment by samuelcolvin** [comment]
looks like build is failing anyway, I'll try and have a look and fix soon.

**Comment by homeworkprod** [comment]
For the record: v0.5.0 comes with wheels for Python 3.9.

Thanks again!
