### ISSUE TITLE
Error when serializing dates and times

### ISSUE THREAD

**Issue by hukkin** [samuelcolvin/rtoml#27]
rtoml version: 0.7.0

Running this
```python
import rtoml
rtoml.dumps(rtoml.loads("time = 23:30:59"))
```
Errors with
```
_rtoml.TomlSerializationError: time is not serializable to TOML: datetime.time(23, 30, 59)
```

**Comment by samuelcolvin** [comment]
Looks like we don't currently process times.

PR welcome

**Comment by hukkin** [comment]
Same issue with dates it seems:
```python
rtoml.dumps(rtoml.loads("date = 2021-01-01"))
```

**Comment by samuelcolvin** [comment]
Ye, not yet implemented.

They need adding like datetime:

https://github.com/samuelcolvin/rtoml/blob/ccd2c01a210bcd3b7cf0be8dbbdedab352476e32/src/lib.rs#L151-L161
