### ISSUE TITLE
Empty table key should be allowed

### ISSUE THREAD

**Issue by pwwang** [samuelcolvin/rtoml#39]
```python
>>> import tomli
>>> tomli.loads('"" = "abc"')
{'': 'abc'}
```
```python
>>> import rtoml
>>> rtoml.loads('"" = "abc"')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    rtoml.loads('"" = "abc"')
  File "/path/to/python3.9/site-packages/rtoml/__init__.py", line 34, in
 loads
    return _rtoml.deserialize(toml)
_rtoml.TomlParsingError: empty table key found at line 1 column 1
```

Reference:

https://github.com/pwwang/toml-bench#testcompliancevalid

**Comment by samuelcolvin** [comment]
Thanks, I'll have a look. Might be a problem with the rust-toml library.

**Comment by samuelcolvin** [comment]
Ignore that, looks like it was fixed in https://github.com/alexcrichton/toml-rs/pull/373.

Updating to use the latest version of toml-rs should fix this.

Will do soon, or PR welcome.

**Comment by samuelcolvin** [comment]
Package is updated, I'd love to new benchmarks with v0.8.

**Comment by pwwang** [comment]
I have updated https://github.com/pwwang/toml-bench to 0.0.3 with rtoml 0.8

**Comment by samuelcolvin** [comment]
Amazing, thanks so much.

**Comment by pwwang** [comment]
@samuelcolvin Thank you for making `rtoml` available in python. 

It's my favorite toml package in python now and I have been replacing other toml packages with `rtoml` in my projects. Not only because of its speed but your attitude toward keeping interpreting `None` to `"null"` (https://github.com/samuelcolvin/rtoml/pull/31#issuecomment-962438561), which gives us the opportunity to trace all the keys.

Looking forward to this implementation: https://github.com/samuelcolvin/rtoml/issues/23#issuecomment-917640979

**Comment by samuelcolvin** [comment]
No problem.

PR welcome if you're like to implement that.

I assume the PR open now does not work for you?

**Comment by thiswillbeyourgithub** [comment]
Hi, is this solved? I think I'm running into this issue and have been for a while now, lurking here and there think this would be about to be fixed.

In my case I can dump fine when when I load I get `_rtoml.TomlParsingError: expected a table key, found a right bracket at line 1 column 3` and sure enough the file begins with
``` toml
[[]]
role = 'user'

```

Am I doing something wrong?
