### ISSUE TITLE
Feature Request: Add support for s390x

### ISSUE THREAD

**Issue by wbappz** [samuelcolvin/rtoml#44]
Building wheel for rtoml (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-s390x-cpython-310
      creating build/lib.linux-s390x-cpython-310/rtoml
      copying rtoml/__init__.py -> build/lib.linux-s390x-cpython-310/rtoml
      copying rtoml/py.typed -> build/lib.linux-s390x-cpython-310/rtoml
      running build_ext
      running build_rust
      error: can't find Rust compiler

Could you add support for s390x?

**Comment by messense** [comment]
Should be easy to add now that `rtoml` uses `maturin`. `maturin-action` has support for cross compiling to any of the manylinux supported architectures: https://github.com/PyO3/maturin-action#manylinux-docker-container

**Comment by samuelcolvin** [comment]
Thanks, happy to accept a PR. Otherwise, I'll try to get to it.
