### ISSUE TITLE
Wheel for Windows for python 3.11

### ISSUE THREAD

**Issue by pwwang** [samuelcolvin/rtoml#63]
Is there any chance for us to build the wheel for Windows for python 3.11 while publishing it?

In order to create it for the user, the installation of `rust` and Microsoft C++ Build Tools is necessary, which can be quite burdensome.

Related: https://github.com/pwwang/datar/issues/180

**Comment by samuelcolvin** [comment]
The best solution would be https://github.com/PyO3/maturin-action/issues/166 - if we get that built, I would definitely be keen.

**Comment by ofek** [comment]
This can be closed https://pypi.org/project/rtoml/#files
